# This workflow will upload a Python Package using uv and pyproject.toml when a release is created
# For more information see: https://docs.astral.sh/uv/

name: Upload Python Package

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"
    
    - name: Set up Python
      run: uv python install
    
    - name: Clean all build artifacts and caches
      run: |
        rm -rf dist/
        rm -rf build/
        rm -rf *.egg-info/
        rm -rf .eggs/
        find . -type d -name __pycache__ -exec rm -rf {} + || true
        find . -type f -name "*.pyc" -delete || true
    
    - name: Build package with uv
      run: uv build
    
    - name: Verify package metadata
      run: |
        uv run python -m pip install twine
        uv run python -m twine check dist/*
    
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@v1.8.14
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
